#pragma once

#include "string.c"

typedef enum {
    TokenIllegal,
    TokenEof,
    TokenComment,
    TokenEnter,
    TokenSemiColon,
    TokenColon,
    TokenComma,
    TokenEqual,
    TokenAssign,
    TokenPlus,
    TokenPlusEqual,
    TokenMinus,
    TokenMinusEqual,
    TokenMultiply,
    TokenMultiplyEqual,
    TokenDivide,
    TokenDivideEqual,
    TokenLess,
    TokenLessEqual,
    TokenGreater,
    TokenGreaterEqual,
    TokenIncrement,
    TokenDecrement,
    TokenParenL,
    TokenParenR,
    TokenBracketL,
    TokenBracketR,
    TokenCurlyL,
    TokenCurlyR,
    TokenBang,
    TokenQuestion,
    TokenDot,
    TokenIdentifier,
    TokenString,
    TokenNumber,
    TokenRange,
    TokenPound,
} TokenType;

char *tokentype_string[] = {
    "TokenIllegal",
    "TokenEof",
    "TokenComment",
    "TokenEnter",
    "TokenSemiColon",
    "TokenColon",
    "TokenComma",
    "TokenEqual",
    "TokenAssign",
    "TokenPlus",
    "TokenPlusEqual",
    "TokenMinus",
    "TokenMinusEqual",
    "TokenMultiply",
    "TokenMultiplyEqual",
    "TokenDivide",
    "TokenDivideEqual",
    "TokenLess",
    "TokenLessEqual",
    "TokenGreater",
    "TokenGreaterEqual",
    "TokenIncrement",
    "TokenDecrement",
    "TokenParenL",
    "TokenParenR",
    "TokenBracketL",
    "TokenBracketR",
    "TokenCurlyL",
    "TokenCurlyR",
    "TokenBang",
    "TokenQuestion",
    "TokenDot",
    "TokenIdentifier",
    "TokenString",
    "TokenNumber",
    "TokenRange",
    "TokenPound", 
};

typedef struct {
    TokenType type;
    String s;
} Token;
